-- ============================================================
-- CRM Nossa Ótica - Migration 032: número da O.S. digitado pela loja
-- ============================================================
-- A ótica já tem a numeração dela (o bloco de O.S. impresso). O app criava um
-- número próprio e não deixava escolher: a mesma ordem ficava com dois números,
-- o do papel e o da tela.
--
-- GENERATED ALWAYS recusa qualquer valor vindo de fora; BY DEFAULT continua
-- numerando sozinho quando a loja não digita nada.

ALTER TABLE public.service_orders
  ALTER COLUMN os_number SET GENERATED BY DEFAULT;

-- Sem isso, dois pedidos podem receber o mesmo número da loja.
ALTER TABLE public.service_orders
  ADD CONSTRAINT service_orders_os_number_unique UNIQUE (os_number);

-- Número digitado à mão não move a sequência, e a próxima O.S. automática
-- nasceria repetindo um número já usado. O gatilho reencosta a sequência no
-- maior número existente depois de cada gravação.
-- SECURITY DEFINER: `setval` exige UPDATE na sequência, que o authenticated
-- não tem (a migration 025 concede só USAGE/SELECT).
CREATE OR REPLACE FUNCTION public.service_orders_keep_number_sequence()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  seq TEXT;
  maior BIGINT;
BEGIN
  seq := pg_get_serial_sequence('public.service_orders', 'os_number');
  IF seq IS NOT NULL THEN
    SELECT MAX(os_number) INTO maior FROM public.service_orders;
    IF maior IS NOT NULL THEN
      PERFORM setval(seq, maior);
    END IF;
  END IF;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS service_orders_number_sequence ON public.service_orders;
CREATE TRIGGER service_orders_number_sequence
  AFTER INSERT OR UPDATE OF os_number ON public.service_orders
  FOR EACH ROW EXECUTE FUNCTION public.service_orders_keep_number_sequence();
